### ISSUE TITLE
Update Heroku App 

### ISSUE THREAD

**Issue by dantrevino** [universelabs/universe-auth#4]
Build from universelabs/universe-auth, instead of dantrevino/universe-auth

**Comment by guylepage3** [comment]
@dantrevino Can you explain what this is a bit more? Are we not using universelabs/universe-auth?

**Comment by guylepage3** [comment]
@dantrevino Can you explain what this is a bit more? Are we not using universelabs/universe-auth?

**Comment by guylepage3** [comment]
Closing
