### ISSUE TITLE
Transfer MongoDB to UniverseLabs.  

### ISSUE THREAD

**Issue by dantrevino** [universelabs/universe-auth#6]
Currently the production cluster is running under dantrevino@gmail.com account.

**Comment by guylepage3** [comment]
Ahh.. I'll create an account for Universe Labs right now.

**Comment by guylepage3** [comment]
Hey @dantrevino I've created a Digital Ocean Team account. Can you transfer your droplet to the team account for @modkaffes? Thank you sir.

@dantrevino @modkaffes @itamarreif @faddat , I've invited you all via your universe.engineering accounts to the Digital Ocean Team Account. Please accept the invitation. Thx.

**Comment by dantrevino** [comment]
It looks like there is not transfer function for DO.  I'll just set up a droplet.

**Comment by guylepage3** [comment]
Perfecto. Closing this issue. Thank you sir.
